---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-single
  labels:
    app: es-single
spec:
  replicas: 1
  selector: 
    matchLabels:   
      app: es-single
  template:
    metadata:
      name: es-single-pod
      labels:
        app: es-single
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
        imagePullPolicy: IfNotPresent
        name: es-single
        ports:
        - name: es-port
          containerPort: 9200
        - name: es-tran-port
          containerPort: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: es-service
  labels:
    app: es-service
spec:
  type: NodePort
  ports:
  - port: 9300
    targetPort: 9300
    name: es-tran-port
  - port: 9200
    targetPort: 9200
    name: es-port
  selector:
    app: es-single
