---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
  name: kibana-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:6.4.0
        ports:
        - containerPort: 5601
          protocol: TCP
        env:
        - name: "ELASTICSEARCH_URL"
          value: "http://10.1.209.48:9200"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: kibana
  name: kibana-service
spec:
  ports:
  - port: 5601
    targetPort: 5601
  selector:
    app: kibana
  type: NodePort