apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "course-nfs-storage" #这里要和storageclass里的name一样
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi