---
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  labels:
    app: init
spec:
  initContainers:
  - name: install
    image: busybox
    command: ["wget","-O","/work-dir/index.html","http://www.baidu.com"]
    volumeMount:
    - name: work-dir #和下面的一个名称
      mountPath: /work-dir
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMount:
    - name: work-dir
      mountPath: /usr/share/nginx/html
  volumes:
  - name: work-dir #对应了上面两个挂载卷，都会挂载再同一地方
    emptyDir: {} #emptydir的存活周期较短

