apiVersion: v1
kind: Pod
metadata:
  name: secret-pod2
spec:
  containers:
  - name: secret2
    image: busybox
    command: ["/bin/bash","-c","ls /etc/config/"]
    volumeMounts:
    - name: secret2
      mountPath: /etc/config/
  volumes:
  - name: secret2
    secret:
      secretName: mysecret #会将mysecret中的两个数据挂载成两个文件:username,password
      items: #指定挂载的位置
        key: username
        path: path/to/username
