apiVersion: v1
kind: Pod
metadata:
  name: secret-pod1
spec:
  containers:
  - name: secret1
    image: busybox
    command: ["/bin/bash","-c","env"]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
    - name: PASSWORD
      valueFrom:
        secreteKeyRef:
        - name: mysecret
          key: password